# Generated by Django 5.0.7 on 2024-07-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
