# Generated by Django 5.0.7 on 2024-08-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraccount_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='last_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
