# Generated by Django 5.0.7 on 2024-08-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
    ]
