# Generated by Django 5.0.7 on 2024-08-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useraccount_posts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/<django.db.models.fields.CharField>'),
        ),
    ]
