# Generated by Django 5.0.7 on 2024-08-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_likes_count_alter_postattachment_image_like_and_more'),
        ('users', '0011_alter_useraccount_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, to='post.post'),
        ),
    ]
