# Generated by Django 5.0.7 on 2024-09-05 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_useraccount_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='suggested_people',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
