# Generated by Django 5.0.7 on 2024-09-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_useraccount_suggested_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
