# Generated by Django 5.0.7 on 2024-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
