# Generated by Django 5.0.7 on 2024-10-04 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_otp_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="following",
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="suggested_people",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
