# Generated by Django 5.0.7 on 2024-09-23 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_popularpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="popularpost",
            name="calculated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
