# Generated by Django 4.2.16 on 2024-11-16 23:07

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='image',
            field=models.ImageField(upload_to=post.models.post_attachment_upload_to),
        ),
    ]
